### ISSUE TITLE
DRAM code missing from sun8i*

### ISSUE THREAD

**Issue by oliv3r** [allwinner-zh/bootloader#1]
I seem to be missing the DRAM init code for the newer sun8i platforms, only a libdram binary file is available, I guess the wrong file was added for upload

Please remove the libdram binary and add the relevant source code files.

Thanks!

**Comment by plaes** [comment]
List of `libdram` binaries in the current (2014.01.15 /a42efe89898c465e4bbfc0cc9fde76d3060ed8df ) source tree:

```
./arch/arm/cpu/armv7/sun8iw8/dram/libdram
./arch/arm/cpu/armv7/sun8iw7/dram/libdram
./arch/arm/cpu/armv7/sun8iw6/dram/libdram-pad
./arch/arm/cpu/armv7/sun8iw6/dram/libdram-homlet
./arch/arm/cpu/armv7/sun8iw5/dram/libdram
./arch/arm/cpu/armv7/sun9iw1/dram/libdram
```

**Comment by plaes** [comment]
The commit introducing these binaries (`a42efe89898c465e4bbfc0cc9fde76d3060ed8df`) was amended and push forced with a new hash `efb9b440d0e8822eac6247bb1213e314f141d103`.

And the binaries are now gone from the repository. If anyone wants them for analysis, ask me :)

**Comment by plaes** [comment]
Given that one of the binaries contained functions like `axp808_probe` and `axp809_probe`, there's definitely some code missing from this repository.

**Comment by oliv3r** [comment]
With the missing libdram, the code either does either not compile, or won't work and thus is not compliant and not the same as the code that is shipped.

**Comment by allwinner-zh** [comment]
Libdram is needed by the boot0, but not u-boot. We will upload the boot0 binary file later, with no GPL issues.
U-boot can be compiled without libdram.

**Comment by vishnupatekar** [comment]
allwinner-zh,
When are you going to release boot0 ?

**Comment by allwinner-zh** [comment]
boot0 source code has been uploaded to basic_loader.

**Comment by oliv3r** [comment]
I'm very very happy to say, this issue has been solved.

Well done allwinner! Well done! Let us now work on the rest :D
