### ISSUE TITLE
u-boot NAND code is missing license indication

### ISSUE THREAD

**Issue by hno** [allwinner-zh/bootloader#4]
There is no indication of which license the NAND code is licensed under. Only "All rights reserved" which means "not licensed for any use".

Please decide which license the code is liensed by and add suitable markers to file headers indicating this. For example if the code is licensed using GPLv2+ like most of the code in u-boot and Linux kernel then add a line stating this in the header of each file.

SPDX-License-Identifier:     GPL-2.0+

Previously a full license header was required, but since some time back u-boot uses SPDX license identifiers to notify which license each file is licensed by. See http://git.denx.de/?p=u-boot.git;a=blob;f=Licenses/README;hb=HEAD for further details.

**Comment by allwinner-zh** [comment]
Thank you for your suggestion, we have changed the license to GPLv2.
