### ISSUE TITLE
mainline u-boot and LIBDRAM source code.

### ISSUE THREAD

**Issue by vishnupatekar** [allwinner-zh/bootloader#5]
Hello,
I've found the A33 DRAM source code at below location:
https://github.com/realthunder/a33_bootloader/tree/master/basic_loader/bsp/bsp_for_a67

I've been working on adding support for A33 to u-boot mainline. have a look at latest two commits at:
https://github.com/vishnupatekar/u-boot-sunxi/tree/a33-dram

This code has been ported to mainline u-boot and it is working. However, It can not accepted in mainline u-boot unless it is released under GPL.

Could you please release the LIBDRAM source code under SPDX-License-Identifier: GPL-2.0+?

**Comment by allwinner-zh** [comment]
We have release the code with GPLv2, and upload to the basic_loader.

**Comment by vishnupatekar** [comment]
Thank you Allwinner!!!

Really appreciated!
